apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 24h
  chart:
    spec:
      chart: velero
      version: 7.2.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
      interval: 24h
  values:
    kubectl:
      image:
        repository: registry.k8s.io/kubectl
        tag: v1.31.0

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    configuration:
      backupStorageLocation:
        - provider: aws
          bucket: isaaclhk-homelab-bucket
          prefix: disaster-recovery
          config:
            region: ap-southeast-1

    credentials:
      existingSecret: aws-credentials

    deployNodeAgent: true

    schedules:
      daily-cluster-backup:
        disabled: false
        schedule: "0 2 * * *"
        template:
          ttl: "24h"
          includedNamespaces:
            - "*"
          defaultVolumesToFsBackup: true
