apiVersion: v1
data:
    token: ENC[AES256_GCM,data:o/1sH6TPkCLFsrLCbbfDYPX9QJvZKp13wXZ6gF9UoK4ysUAASdPZeOp8YKTfFDBioUHX3RYXaNlroDl6rZV5dV9WGq7hY6Ub0lFLRWC9ULI4bKcx+f/cdZRBNyzgqx4A2R0+gBQzAQP/aojoIXq3Z7MesXN/tcPVw/VjxVRhPrBvP+7SK7boEwI2vIDKrr+M7kd5wPZA8LBdCsV0oUo0bs7nH9pQucNIu8Bvo8kYhv+AXdG5SHs2bTViz9z3B+mLAIuy9T/zhF2PX18jxKuSf1s+3Fdbc60Lmo+8HZ/2ctqOBTa5hbHk8lfPp0VZMBRt1Ml0S+ZGVAU=,iv:cbh97ouMsB1tCiGGfMZZZQ6wfgEQUERxJ0G779SV5uk=,tag:1m11x7lAMGgOFazhO4c7cQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-token
    namespace: homarr
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByR2loQkpEN3QvaEczV3hm
            Snl3QjE1WGN4RTlZVk9HWGJabGhZQktLbnlRCmVvc3NqK0RKdnJENVRZQTQyekFl
            YythejZsb21wUUkyeVhkZUtpTUdkeEkKLS0tIFdmMnJGSURlVkthTzd6N3NkVURP
            dEFmNGF1M1d1UytDOUVOU0phNlRMZ2cKWLXNZASQDNuUARaUwJpYXMM/MVRP8Pyd
            qd+0n0w1jp/oYMn/wC0N2BArvSIsw9NPag7pndNbQd2KjPjM/SmxVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T08:45:33Z"
    mac: ENC[AES256_GCM,data:0QQhZi2SvrhIiBrwtJQcfQv97FI+rv9oJxshSffEFR1VXxbPU/kSS4oXKhOeUOZPcxx1piPSQRWdqjL/xjw7iD6lTao0kLvEgoUlxt4unyLWyd1RX8IeFKBaUbMnIHXXFBcFhiAmR0dy2mEfCnXc8OR2LsJddaO6cw0m6zMChtA=,iv:N7SgbwM+CBu4s6MiPF8IQYK4jcpD06zD8A4SQxa9EdM=,tag:K8+DjckejKAqHa8G2Xky/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
