apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 24h
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 24h
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: "1"
    defaultSettings:
      defaultReplicaCount: "1"
