apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:41.131.5
              name: renovate-bot
              envFrom:
                - secretRef:
                    name: renovate-env
              envFrom:
                - configMapRef:
                    name: renovate-configmap
          restartPolicy: Never
