apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:41.173.1
              name: renovate-bot
              envFrom:
                - secretRef:
                    name: renovate-secret
                - configMapRef:
                    name: renovate-configmap
          restartPolicy: Never
