apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:97jsf7gqrFvC5BxVtWvP1ezZOb3/L9KeOxypkbDp8iNsC/HCtRbU6g==,iv:FIYIbtR2Uk/7YJp1EfgVkl1xrbDeriOFqjtNaHwtScU=,tag:F9wHcCjhVkmkN3y8DpJC5A==,type:str]
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbFRvZEx2cFRKdjM3Y3BP
            U0ZHZ0IxQUw3MzNheVZzZnhuUXZSaXRESjJjCkhkMDdweHZmUGRJMmNPdHpzK25x
            V29ENGdMMVU5L2hCQk5nTGtsdFNudUUKLS0tIDhrR0ZZOFU0OTFQazc4bzA0ZkFs
            ZUkvRW1YRFI3NUZCaVJZcjNGWWk2ME0KB7nRRaBQm3D19wkAiMgug/ag7FVyLKei
            ACW/RjJ5vFgmv9Q15e/2ETl8ycw5NbcjcjUgy/EHVOx3y82erZbMGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T15:35:21Z"
    mac: ENC[AES256_GCM,data:GgyHcBMlXynmkBTrfRL4Qs620COA9uftwZj8wrsaaMqvNI9QODv9Rr1flWszDgMqjEK+dxSEAXor4pvuGHCPfSgoOJFhJxxYctoDYZ5IX/AvJhVa7nHHuSOexQrXfQodtOSGMYl/Gys54TPT7QshvnN64M5VL+yYM39Mn/8xyuc=,iv:QlXkcZYDrfQz9pqBbZDV2L91beJm8jeUIGY3z1256aU=,tag:wWZvy63I+yTuSzOX8BQ/QA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
