apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:pvESp96NN1p3rhu7b8Y+P89Uo55OOz4N5F/SLS18FtY42/YxuIZ7huW3A377vCMNMHtB6+B1jmk=,iv:gYWIvfMukzGVm67fYKjGzUaGOXogYMs1yQR2u/Os4Mw=,tag:YPNeVYm/WE6HLouU2tPMtg==,type:str]
kind: Secret
metadata:
    name: renovate-secret
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUenovUkJCTlB1bG5ZYUxJ
            U0EwMG5ILzU4TWxEWlNQWXNnL1ZaNndwMG5jCkVRS1Z6S2tvRzZTbGx6RVduMXZV
            WGxCVmpZUlp4bEhmeVhpUGwzbUFwMFUKLS0tIDhydHJOV1ViQ3BIT09MNjhSblg5
            SnJtZVdLZlIydEtuUUFkTjBCK0VsT0UKziaKC1L3mCcMh8YMT1uPoTjMN9tfSjXn
            IocG0mlDf74/lUY7sNN6Hs/CTLWewzJ8ZU5tU6eczvzPyl21zTUNFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T14:43:30Z"
    mac: ENC[AES256_GCM,data:eklKG0Avfgcx46vL3Xb76F48F14+aYDPGnHwnmONL1qtbhUhY8AuzzVF3I3hxlKrQsrQKCcI0Oz4wEJYpvxXfhsusJVO5YpZhIyrXos6UHxKoGq166iRes5g4ZBBnuzEaf24TELJtVpfpOFPtwCSTXvDlZc5MMHkGS1EMU5pAzs=,iv:/EtCfv7Ewza5VB1jnvXHy/ymOG7kVqDyS1odHmPFDHU=,tag:pCJcTi4lJOOGzI20p81Wkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
