apiVersion: v1
data:
    GITHUB_TOKEN: ENC[AES256_GCM,data:h7e+GxSl4SrwULpIY9KX34JXZPwsxCCzfvZvcnVOdotjErB2oI9a6jTuf9lNaln0qyHW/JoHeSs=,iv:WWhZcBIg810tDEbtFHt4guRcIYkbz89K3xxb6ex35P0=,tag:UmESZ6tcoD2gj6tu6TIc7Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-secret
    namespace: renovate
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SW5uYUhuaCs4VWFRTDMz
            VUlzWVVYWlh3QmVtUGpJNzdTNDR2SENnM1VVCnZhYjRxeWpXeUIwWE9Ua0F6cHhE
            M0dLTkFwUjhKWTRYZW51b1BNbitpK1EKLS0tIHJFV1hEdytuUzVmQ2M4RDYxZG1W
            eGR6aWpSUDZ0ZGV4R3dLKzBLTjRwaHMKaDzAHR+x0ExutmWj7dMGjDu/B5wNm3WT
            4b0QTW9Ov6Ai/N/vn1pbsdAJ6KimGriO1Dtkk2HhAz8tVex+gmAaSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T14:16:27Z"
    mac: ENC[AES256_GCM,data:q3bbs4ff4Em4GBCPLWpAdT8j5WjFIKt9ANPgMz4oEJ7K1YGHftwfaPzN0SuXVaZ0QGxXB+SGY9wBgwAmdHjYeaD8hDhXJNUbaXzzlXI5NwF1FEGQUmDnL010w3kM2Y4dQCmqCnBDVwiVJyMjHI3oO68qVoRiasu5h+MLTmXtwn4=,iv:BGj+SFvBQla5yfypm1xlkSz5DL4Rb5CB+5jP+7BMwbE=,tag:GZXMMhHRGkVbifFIFWROag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
