apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  timeout: 3m
  chart:
    spec:
      chart: homarr
      version: "5.*"
      sourceRef:
        kind: HelmRepository
        name: homarr
      interval: 24h
  releaseName: homarr
  values:
    replicaCount: 1
    rbac:
      enabled: true
    persistence:
      homarrDatabase:
        enabled: true
        storageClassName: local-path
        mountPath: /app/data
        size: 500Mi
